import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import { MetaMaskProvider } from "@metamask/sdk-react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {/*<MetaMaskProvider*/}
        {/*    debug={false}*/}
        {/*    sdkOptions={{*/}
        {/*        dappMetadata: {*/}
        {/*            name: "BDA Dapp by Zdenek Lapes",*/}
        {/*            url: window.location.href,*/}
        {/*        },*/}
        {/*        infuraAPIKey: process.env.INFURA_API_KEY,*/}
        {/*    }}*/}
        {/*>*/}
        {/*</MetaMaskProvider>*/}
        {children}
        </body>
        </html>
    );
}
